# Read the Docs configuration file

# Required by rtd config v2
version: 2

build:
    image: latest

python:
    version: 3.7
    install:
        - requirements: docs/requirements.txt
        - method: setuptools
          path: astroNN