language: python

env:
  global:
    - SDSS_LOCAL_SAS_MIRROR=/home/travis/build/henrysky
    - GAIA_TOOLS_DATA=/home/travis/build/henrysky
  matrix:
    - LATEST_FLAG=true KERAS_VER='2.2.0' TF_VER='1.8.0'  # latest version config
    - LATEST_FLAG=false KERAS_VER='2.1.6' TF_VER='1.7.0'  # previous latest version config

python:
  - "3.6"

before_install:
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y graphviz  # For model plotting

install:
  - pip install coverage
  - pip install coveralls
  - pip install keras==$KERAS_VER  # because keras is not in compulsory requirement
  - pip install tensorflow==$TF_VER  # because tensorflow is not in compulsory requirement
  - pip install pydot
  - pip install graphviz

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
  - python setup.py install
  - coverage run --source=astroNN -m unittest discover -s tests

after_success:
  - if [ $LATEST_FLAG == true ]; then coveralls  # To upload reports to coveralls.io

notifications:
  slack:
    on_success: change