language: python

env:
  global:
    - SDSS_LOCAL_SAS_MIRROR=/home/travis/build/henrysky
    - GAIA_TOOLS_DATA=/home/travis/build/henrysky
    - LASMOT_DR5_DATA=/home/travis/build/henrysky
  matrix:
    - LATEST_FLAG=true USE_KERAS=true KERAS_VER='2.2.4' TF_VER='1.11.0' TFP_VER='0.4.0'  # latest version config
    - LATEST_FLAG=false USE_KERAS=true KERAS_VER='2.2.0' TF_VER='1.10.0' TFP_VER='0.3.0'  # previous latest version config
    - LATEST_FLAG=false USE_KERAS=false KERAS_VER='0.0.0' TF_VER='1.11.0' TFP_VER='0.4.0'  # latest tensorflow only without keras

python:
  - "3.6"

before_install:
#  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y graphviz  # For model plotting

install:
  - pip install coverage
  - pip install coveralls
  - if [ $USE_KERAS == true ]; then pip install keras==$KERAS_VER; fi  # because keras is not in compulsory requirement
  - pip install tensorflow==$TF_VER  # because tensorflow is not in compulsory requirement
  - pip install tensorflow-probability==$TFP_VER --no-deps  # because tfp is not in compulsory requirement
  - pip install pydot
  - pip install graphviz
  - python setup.py install

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
  - if [ $LATEST_FLAG == true ]; then coverage run --source=astroNN -m unittest discover -s tests; fi  # Run all tests for latest config
  - |
    if [ $LATEST_FLAG == false ] && [ $USE_KERAS == true ]; then coverage run --source=astroNN -m unittest \
    tests.test_layers tests.test_loss_func tests.test_models tests.test_apogee_model; fi  # Run partial tests for non latest config
  - |
    if [ $LATEST_FLAG == false ] && [ $USE_KERAS == false ]; then coverage run --source=astroNN -m unittest \
    tests.test_layers tests.test_loss_func tests.test_models tests.test_apogee_model; fi  # Run partial tests for non latest config

after_success:
  - coveralls # To upload reports to coveralls.io

notifications:
  slack:
    on_success: change