language: python
python:
  - "3.6"
install:
  - pip install coverage  # Add me to install python-coveralls
  - pip install keras  # because keras is not in compulsory requirement
  - pip install tensorflow  # because tensorflow is not in compulsory requirement

script:
  - python setup.py install
  - python -m unittest discover -s tests

after_success:
  - coveralls  # Add me to upload reports to coveralls.io

notifications:
  slack:
    on_success: change