language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install python-coveralls  # Add me to install python-coveralls
script:
  - python setup.py install
  - pip install coverage       # Add me to install coverage.py
after_success:
  - coveralls                     # Add me to upload reports to coveralls.io